apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: stable
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-04-09T11:53:24Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app.kubernetes.io/instance: stable
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 7.4.5
    helm.sh/chart: grafana-6.6.4
  name: stable-grafana
  namespace: default
  resourceVersion: "8222"
  selfLink: /api/v1/namespaces/default/services/stable-grafana
  uid: 7ebeb0da-858f-4232-8904-560e7ce83c5b
spec:
  clusterIP: 100.65.58.48
  externalTrafficPolicy: Cluster
  ports:
  - name: service
    nodePort: 31258
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: stable
    app.kubernetes.io/name: grafana
  sessionAffinity: None
  type: LoadBalancer