apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: stable
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-04-09T11:53:24Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/managed-by: Helm
    chart: kube-prometheus-stack-14.5.0
    heritage: Helm
    release: stable
    self-monitor: "true"
  name: stable-kube-prometheus-sta-prometheus
  namespace: default
  resourceVersion: "7902"
  selfLink: /api/v1/namespaces/default/services/stable-kube-prometheus-sta-prometheus
  uid: 9042a504-d25f-4122-b6aa-52ed5e53b576
spec:
  clusterIP: 100.67.172.242
  externalTrafficPolicy: Cluster
  ports:
  - name: web
    nodePort: 31942
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus
    prometheus: stable-kube-prometheus-sta-prometheus
  sessionAffinity: None
  type: LoadBalancer