apiVersion: v1
kind: Service
metadata:
  name: guitar-service
spec:
  selector:
    app: guitar-app
    environment: ${ENVIRONMENT}
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer