apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  selector:
    app: sonarqube
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9000
  type: LoadBalancer